### ISSUE TITLE
About Immiscible Diffusion

### ISSUE THREAD

**Issue by iamunr4v31** [lucidrains/e2-tts-pytorch#22]
In immiscible diffusion, the noise is selected while minimizing the cost w.r.t the data batch thereby minimizing the variance from the source distribution to the target distribution. In CFM however, we can start from any prior distribution (say, text encoder outputs for TTS). Selecting the prior as described in the paper is not possible because of the mapping between the prior and the target ( I would want a particular text embedding to be mapped to the corresponding mel-spectrogram).

So the algorithm should sample both prior and targets like:

```
let assign_mat

x0 = x0[assign_mat]
x1 = x1[assign_mat]
condition = condition[assign_mat]
```
![image](https://github.com/user-attachments/assets/afb0a89a-055b-4cda-8f34-1356a1756528)

Please correct me if I'm wrong.

**Comment by lucidrains** [comment]
@iamunr4v31 oh yes, i forgot about the condition

however, i've removed it since i wasn't able to see a signal at [this repo](https://github.com/lucidrains/rectified-flow-pytorch)

**Comment by iamunr4v31** [comment]
Interesting. I'm working on something similar at the moment. Will let you know if I have any luck with improving the convergence behavior. But, this is very weird considering the algorithm optimizes for straighter flows.

**Comment by lucidrains** [comment]
@iamunr4v31 try running it at the rectified flow repository (or if you see an issue, please let me know)

if you see something, willing to spend more time on it

**Comment by lucidrains** [comment]
@iamunr4v31 and yes, agreed with the straightening flow connection

**Comment by bfs18** [comment]
@lucidrains Does it improve result. The idea is similar to [Improving and generalizing flow-based generative models with minibatch optimal transport](https://arxiv.org/abs/2302.00482), but applied to a larger dataset. I did not observe improvement on the vocoder task; I guess the mel condition is so sufficient that the conditional mapping is already close to a one-to-one map.

**Comment by lucidrains** [comment]
@bfs18 yes, i saw some improvements on [small scale image generation](https://github.com/lucidrains/rectified-flow-pytorch)

**Comment by bfs18** [comment]
@lucidrains I'm glad to hear about the positive results on image generation! I'll look into it further.
