### ISSUE TITLE
sigma

### ISSUE THREAD

**Issue by skirdey** [lucidrains/e2-tts-pytorch#31]
https://github.com/lucidrains/e2-tts-pytorch/blob/9d5fc1b4fe6e0fecd0e5e43681be0c6d2d1732ec/train_example.py#L32-L39

Should we have default value of sigma = 0.1 for the training case? It is not explicitly mentioned in the paper, but it seems like a good candidate to add a bit of variance during training.

**Comment by JingRH** [comment]
> https://github.com/lucidrains/e2-tts-pytorch/blob/9d5fc1b4fe6e0fecd0e5e43681be0c6d2d1732ec/train_example.py#L32-L39
> 
> Should we have default value of sigma = 0.1 for the training case? It is not explicitly mentioned in the paper, but it seems like a good candidate to add a bit of variance during training.


In many flow matching networks, sigma is actually set to zero.

**Comment by lucidrains** [comment]
@skirdey seeing anything on your end?

**Comment by skirdey** [comment]
nothing specific yet, just a thought, i am trying it on a few smaller runs atm

**Comment by lucidrains** [comment]
@skirdey oh strange, thought you'd hit a positive result by now

**Comment by lucidrains** [comment]
@skirdey maybe start with the dataset Lucas used, and once you see what he sees, then titrate up to your large multilingual one?
