### ISSUE TITLE
About concatenation VS addition

### ISSUE THREAD

**Issue by juliakorovsky** [lucidrains/e2-tts-pytorch#32]
In the paper they say: "The input to the mel spectrogram generator is m ⊙ sˆ, yˆ, the flow step t, and noisy speech st. yˆ is first converted to character embedding sequence. **Then, m ⊙ sˆ, st, y˜ are all stacked to form a tensor with a shape of
(2 · D + E) × T**, followed by a linear layer to output a tensor with a shape of D × T. In your code I found this line: https://github.com/lucidrains/e2-tts-pytorch/blob/9d5fc1b4fe6e0fecd0e5e43681be0c6d2d1732ec/e2_tts_pytorch/e2_tts.py#L796

Do I understand it right: they talk about concatenation and you do addition? I wasn't able to find where dimension would be (2 · D + E) × T in your code.

**Comment by lucidrains** [comment]
@juliakorovsky yes that's right, they brought this design over from voicebox

think this is one of those details that matters very little

**Comment by lucidrains** [comment]
i can add the concat way for completeness sake, let's leave the issue open.
