### ISSUE TITLE
About classifier-free guidance (CFG)

### ISSUE THREAD

**Issue by SuperiorDtj** [lucidrains/e2-tts-pytorch#35]
The paper on e2tts states that during training, text conditions are discarded with a probability of 20%, but during inference, the CFG scale is set to 1. Based on my understanding of the CFG formula, this value does not account for the removal of unconditional samples, meaning that CFG is ineffective. Is it that the CFG formula used in the paper is different, or does it indicate that CFG is not performing well, leading to the final choice of CFG=1?
<img width="953" alt="image" src="https://github.com/user-attachments/assets/2c4af8c1-7654-41fa-8fe7-d397bec5f50d">

**Comment by SWivid** [comment]
last line should be
model_output = model_t + scale * (model_t - model_uncond)

you could double check the cfg definition and formula

**Comment by SuperiorDtj** [comment]
> last line should be model_output = model_t + scale * (model_t - model_uncond)
> 
> you could double check the cfg definition and formula

Thank you for your reply. It seems that this is due to differences in code implementation between different projects.
