### ISSUE TITLE
predicted mel returned by E2TTS classes's forward function

### ISSUE THREAD

**Issue by AnkurVerma02** [lucidrains/e2-tts-pytorch#36]
https://github.com/lucidrains/e2-tts-pytorch/blob/f37c210c9d5539145b521f45540ef9632e01fab1/e2_tts_pytorch/e2_tts.py#L1171

In the above line, shouldn't we return the predicted mel as pred+x0, as pred is just the difference between the input and target distribution learned by the model, and instead the actual prediction will be pred+x0?

**Comment by lucidrains** [comment]
@AnkurVerma02 hey Ankur, yes i can return the predicted mel, in the case that you are doing some audio perceptual loss on top (which is a proven technique)

you need to account for time, as you could be anywhere between full noise and full data. it would be `pred + x0` if the time were set at `0.` - the actual predicted mel is `pred * (1. - times) + x0`

**Comment by lucidrains** [comment]
oh oops, `x0` is the full noise, yes you are correct 🤦

**Comment by lucidrains** [comment]
@AnkurVerma02 i see why you were confused, the flow was being logged rather than the actual mel prediction

should be fixed [here](https://github.com/lucidrains/e2-tts-pytorch/commit/7969f7acc986580c2d425ddb03257c8a03391127#diff-b89afce3fea7a9b3b77dd7179b080bf9fdbe0eee5863029f92ace824827da4afR245)
