### ISSUE TITLE
Why did you change flow formula?

### ISSUE THREAD

**Issue by juliakorovsky** [lucidrains/e2-tts-pytorch#39]
I wanted to ask about this commit: https://github.com/lucidrains/e2-tts-pytorch/commit/953a3b672b8089e7b61e696ddf1468006ac70537#diff-aa4e45ab239723e4fe2411800a686d4b7d1a7235044da0fec1ce924182e03aceR989

Why did you change these formulas? For example, formula for flow? Does it help with convergence? What is the reasoning behind this?

**Comment by skirdey** [comment]
It was just a simplification as sigma doesn't seem to affect much and in the original paper on audio flow matching, as far as i remember, it was set to 0.

**Comment by juliakorovsky** [comment]
> It was just a simplification as sigma doesn't seem to affect much and in the original paper on audio flow matching, as far as i remember, it was set to 0.

So if in my implementation I still have original formula and sigma is 1e-5 it basically doesn't affect anything but does not make training worse either?

**Comment by skirdey** [comment]
most likely
